OS-8594 mdb_v8 update for gcc 14
joyent/mdb_v8 pull request #128
Opened 2024-11-12 21:02 UTC by tsoome

The issue is about local buffer space being too small, we need 25 bytes, not 10.

2024-11-12 21:11 UTC, danmcd submitted a review, later dismissed

2024-11-13 00:21 UTC, bahamat requested changes

2024-11-13 00:21 UTC, bahamat commented on src/mdb_v8.c
This file needs copyright update.

2024-11-13 08:00 UTC, tsoome commented on src/mdb_v8.c
done.

2024-11-13 14:59 UTC, danmcd approved these changes

2024-11-13 16:27 UTC, bahamat approved these changes

2024-11-14 15:05 UTC, merged